name: gap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^12.0.0+1
  http: ^1.3.0
  flutter_plugin_android_lifecycle: ^2.0.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets: []
