name: gap
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'  # Updated to match your current Dart SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  camera: ^0.10.5+5
  google_mlkit_text_recognition: ^0.10.0
  permission_handler: ^11.0.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: []

  # Commented out fonts section as fonts folder is missing
  # fonts:
  #   - family: Poppins Bold
  #     fonts:
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
  #   - family: Poppins Medium
  #     fonts:
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #   - family: Poppins Light
  #     fonts:
  #       - asset: fonts/Poppins-Light.ttf
  #         weight: 500
